[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "audiograb"
version = "0.1.0"
description = "GUI to download YouTube videos and playlists as MP3, using yt-dlp"
readme = "README.md"
license = { text = "GPL-3.0-or-later" }
requires-python = ">=3.10"

dependencies = [
    "yt-dlp>=2022.5.18",
    "PySide6>=6.10.1",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.3.2"
]

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
audiograb = "audiograb.main:main"

[tool.ruff.lint]
select = ["E", "F", "I"]  

